### ISSUE TITLE
 RuntimeException (400)

### ISSUE THREAD

**Issue by diomed** [mblode/grav-theme-medium#1]
Hi!
I get this error when upon activation of this theme:

`RuntimeException (400)
Template "default.html.twig" is not defined.`

D:\wamp\www\grav\system\src\Grav\Common\Twig\Twig.php

**Comment by mblode** [comment]
You would need to copy the pages in the _demo folder. This is because the templates are not the same as Antimatter but rather it is based off of the Cacti Grav theme.  Hope this helps

**Comment by diomed** [comment]
is there no workaround around that, like for theme to grab pages from current folder?
seems redundant to make copies.

**Comment by mblode** [comment]
Hmm Ill ask on Gitter/grav or I could change the templates to match antimatter as it is the default Grav theme. The latter might be a better option.

**Comment by geekjus** [comment]
I'm a bit confused what do I need to copy and to where? I'm having the same `RuntimeException (400) Template "default.html.twig" is not defined. error. 

`

**Comment by mblode** [comment]
In the '_demo' folder, there are pages that should be copied into 'user/pages/'. This will fix the issues
