### ISSUE TITLE
Demo link is dead

### ISSUE THREAD

**Issue by Salvatos** [mblode/grav-theme-medium#10]
The demo link for this theme at getgrav (http://medium.matthewblode.com.au/) redirects to a scam site.

**Comment by mblode** [comment]
Sorry about that. I didn't renew this domain name but I used to own it. I currently do not have a working version of the site at the moment. I will try set one up shortly. I will also remove any links to that domain. Thanks

**Comment by flaviocopes** [comment]
@mblode can you accept https://github.com/mblode/grav-theme-medium/pull/11 and make a new release? Thanks! https://github.com/getgrav/grav/issues/1452

**Comment by flaviocopes** [comment]
Thanks @mblode, you need to make a new release so Grav picks up the changes 👍

**Comment by Sogl** [comment]
@mblode Add new demo link please 😉

**Comment by mblode** [comment]
https://medium.matthewblode.com/
