### ISSUE TITLE
Custom theme based on medium theme?

### ISSUE THREAD

**Issue by ghost** [mblode/grav-theme-medium#16]
### No issues, but a question...

What will happen to the changes in 'src' if I update the theme later? Will they be gone even if I use separate scss/css ? Or, is there a way to use 'medium' theme as base theme for custom theme?

*Thank You!*

**Comment by mblode** [comment]
You should be able to update the 'src' folder and all of the [sass/scss](https://sass-lang.com/) files within that folder. Then you can use [gulp](https://gulpjs.com/) to compile and minify the code which should spit the CSS and minified js out into the 'dist' folder. The base layout page is just looking for the CSS file within the 'dist' folder. Let me know if you need any more help/clarification 😄
