### ISSUE TITLE
Sidebar not shown properly

### ISSUE THREAD

**Issue by pyrophyllit** [mblode/grav-theme-medium#2]
The sidebar is not shown correctly when there are only two posts.

**Comment by mblode** [comment]
Can you send a picture?

**Comment by pyrophyllit** [comment]
Here a screenshot of what I ment. :)
![sidebar](https://cloud.githubusercontent.com/assets/16595256/13136570/f22ab546-d61a-11e5-9ffb-203da339bcab.jpg)

**Comment by pyrophyllit** [comment]
after the update it got worse. Now the sidebar stays at the bottom all the time... no matter how many posts are being displayed.

**Comment by mblode** [comment]
I think I have fixed the problem with the 2.0.1 update
