### ISSUE TITLE
Live-Demo linked from grav-theme Page doesn't work

### ISSUE THREAD

**Issue by BugHunter2k** [mblode/grav-theme-medium#5]
Just noticed the demo linked here
https://getgrav.org/downloads/themes
to
http://medium.matthewblode.com.au/
doesn't work

**Comment by flaviocopes** [comment]
Demo still down :cry:

**Comment by mblode** [comment]
It is back up again 😄  [medium.matthewblode.com.au](medium.matthewblode.com.au)
